site_name: Move Base Flex Documentation
site_url: https://uos.github.io

repo_name: Github
repo_url: https://github.com/magazino/move_base_flex

docs_dir: docs
theme:
    name: material
    features:
      - navigation.instant
      - navigation.tabs

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - admonition

nav:
  - Home: index.md
  - Showcase: showcase.md
  - Getting Started: 
    - Installation: installation.md
    - Tutorials: tutorials/overview.md
  - Tutorials:
    - Beginner: 
      - Welcome: tutorials/beginner/welcome.md
      - Basic Navigation: tutorials/beginner/basic_navigation.md
      - Beyond the Relay - Move Base Flex: tutorials/beginner/beyond_relay.md
      - Path Planning: tutorials/beginner/path_planning.md
      - Parameters and Configuration: tutorials/beginner/parameters.md
    - Advanced: 
      - Welcome: tutorials/advanced/welcome.md
      - Writing a simple SMACH: tutorials/advanced/smach.md
    - Expert: tutorials/expert.md
    - Writing MBF Plugins: tutorials/writing_mbf_plugins.md
    - Mesh Navigation Stack: tutorials/mesh_navigation_stack.md
  - Concepts:
    - Architecture: concepts/architecture.md
    - Navigation Servers: concepts/navigation_servers.md
