site_name: Move Base Flex Documentation
site_url: https://uos.github.io

repo_name: Github
repo_url: https://github.com/magazino/move_base_flex

docs_dir: docs
theme:
    name: material
    features:
      - navigation.instant
      - navigation.tabs

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Home: index.md
  - Showcase: showcase.md
  - Getting Started: 
    - Installation: installation.md
    - Tutorials: tutorials/overview.md
  - Tutorials:
    - Beginner: 
      - Welcome: tutorials/beginner/beginner.md
      - MoveBase to MoveBaseFlex: tutorials/beginner/mb_to_mbf.md
    - Advanced: tutorials/advanced.md
    - Expert: tutorials/expert.md
    - Writing MBF Plugins: tutorials/writing_mbf_plugins.md
    - Mesh Navigation Stack: tutorials/mesh_navigation_stack.md
  - Concepts:
    - Architecture: concepts/architecture.md
    - Navigation Servers: concepts/navigation_servers.md
